/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/app/dashboard/': RouteRecordInfo<'/app/dashboard/', '/app/dashboard', Record<never, never>, Record<never, never>>,
    '/app/tasks/': RouteRecordInfo<'/app/tasks/', '/app/tasks', Record<never, never>, Record<never, never>>,
    '/app/tasks/[taskid]': RouteRecordInfo<'/app/tasks/[taskid]', '/app/tasks/:taskid', { taskid: ParamValue<true> }, { taskid: ParamValue<false> }>,
    '/app/user/': RouteRecordInfo<'/app/user/', '/app/user', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/privacy': RouteRecordInfo<'/privacy', '/privacy', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/tos': RouteRecordInfo<'/tos', '/tos', Record<never, never>, Record<never, never>>,
  }
}
